name: Deploy Book

on:
  push:
    branches:
      - main

jobs:
  release:
    name: GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build the mdbook
        run: |
          cd book
          cargo install mdbook
          cargo install mdbook-admonish
          mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book
